title: Giovanni Cabass
description: Physicist & ML researcher
url: "https://giovanni-cabass.github.io"
baseurl: ""
author: Giovanni Cabass
permalink: /notes/:year/:month/:day/:title/
collections:
  pages:
    output: true
    permalink: /:name/

sass:
  silence_deprecations: [import]

markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
